### ISSUE TITLE
Memory issues in LPD

### ISSUE THREAD

**Issue by AnderBiguri** [ahendriksen/tomosipo#17]
I have the following code (copied from tomosipo's LPD code) that causes an out of memory issue after N iterations. This is a CUDA memory error (not a pytorch one), so I suspect tomosipo is to blame:

```
Traceback (most recent call last):
  File "/mhome/damtp/r/ab2860/perovskiteCT/perovskiteCT/train_LPD_tomosipo.py", line 159, in <module>
    loss.backward()
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

I have tested it in my own implementation of LPD which leads to the same error. If the memory usage of the GPU is inspected, one can see that every N+epsilon batch updates (for a random epsilon<N) a few KB more of memory is allocated in the GPU. Its not fixed, but this can be caused by how pytorch allocates memory. 

This is the full code I used, basically the demo from tomosipo, with my own data. Data is ~5000 512x512 CT images and 360x900 sinograms paired to the images. 

```
import torch 
import tomosipo as ts
from tomosipo.torch_support import (
    to_autograd,
)
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm

import nvidia_smi



torch.cuda.set_device(3)

image=torch.zeros(1,512,512)
vg = ts.volume(shape=image.shape, size=(300/512, 300, 300))
pg = ts.cone(
    angles=360, shape=(1, 900), size=(1, 900), src_orig_dist=575, src_det_dist=1050
)
A = ts.operator(vg, pg)

class PrimalModule(nn.Module):
    def __init__(self):
        super().__init__()
        layers = [
            nn.Conv2d(6, 32, kernel_size=3, padding=1, bias=False),
            nn.ReLU(),
            nn.Conv2d(32, 32, kernel_size=3, padding=1, bias=False),
            nn.ReLU(),
            nn.Conv2d(32, 5, kernel_size=3, padding=1, bias=False),
        ]
        self.block = nn.Sequential(*layers)

    def forward(self, x):
        return self.block(x)

class DualModule(nn.Module):
    def __init__(self):
        super().__init__()
        layers = [
            nn.Conv2d(7, 32, kernel_size=3, padding=1, bias=False),
            nn.ReLU(),
            nn.Conv2d(32, 32, kernel_size=3, padding=1, bias=False),
            nn.ReLU(),
            nn.Conv2d(32, 5, kernel_size=3, padding=1, bias=False),
        ]
        self.block = nn.Sequential(*layers)

    def forward(self, x):
        return self.block(x)

class LearnedPD(nn.Module):
    def __init__(self, vg, pg, n_iters, do_pingpong=False):
        super().__init__()
        self.n_iters = n_iters
        self.vg = vg
        self.pg = pg
        self.do_pingpong = do_pingpong
        
        for i in range(n_iters):      
            # To ensure that the parameters of the primal and dual modules 
            # are correctly distributed during parallel training, we register
            # them as modules. 
            self.add_module(f"{i}_primal", PrimalModule())
            self.add_module(f"{i}_dual", DualModule())
                
    def forward(self, g):
        B, C, H, W = g.shape
        assert C == 1, "single channel support only for now"
        h = g.new_zeros(B, 5, H, W)
        f_primal = g.new_zeros(B, 5, *self.vg.shape[1:])
        
        def dual_step(g, h, f, module):
            x = torch.cat((h, f, g), dim=1)
            out = module(x)
            return h + out
        def primal_step(f, update, module):
            x = torch.cat((f, update), dim=1)
            out = module(x)
            return f + out
        
        ts_op = ts.operator(self.vg[:1], self.pg.to_vec()[:, :1, :])
        op = to_autograd(ts_op)
        opT = to_autograd(ts_op.T)
        def fp(x):
            if self.do_pingpong:
                x = x.cpu()
            return op(x).cuda()
        def bp(x):
            if self.do_pingpong:
                x = x.cpu()
            return opT(x).cuda()
        
        for i in range(self.n_iters):
            primal_module = getattr(self, f"{i}_primal")
            dual_module = getattr(self, f"{i}_dual")
            
            f_dual = fp(f_primal[:, :1])
            h = dual_step(g, h, f_dual, dual_module)
            update = bp(h[:, :1])
            f_primal = primal_step(f_primal, update, primal_module)
            
        return f_primal[:, 0:1]

# DATA
import glob
import tifffile as tif
import skimage

data_dir="/local/scratch/public/myID/data/projections/training/"
I0=2000

# about 5000~
n_files=len(glob.glob1(data_dir,"noise_"+str(I0)+"*.tif"))

image_size=[1,512,512]
y=np.zeros((n_files,1,360,900))
x=np.zeros((n_files,1,512,512))

for img_idx in range(n_files):
    y[img_idx,0]=tif.imread(data_dir+'/noise_'+str(I0)+'_'+f'{img_idx:04}'+'.tif')
    x[img_idx,0]=skimage.transform.resize(tif.imread(data_dir+'/label_img_'+f'{img_idx:04}'+'.tif'),(image_size[1],image_size[2]))
y=torch.from_numpy(y.astype(np.float32))
x=torch.from_numpy(x.astype(np.float32))



# TRAIN
epochs = 50
batch_size = 4
learning_rate = 1e-4
parallel_gpu = False
pingpong = False

training=torch.utils.data.TensorDataset(y,x)
train_dl = torch.utils.data.DataLoader(training, batch_size=batch_size, shuffle=False,pin_memory=True, drop_last=True)

# In practice, parallel_gpu appears to be slower.. 
net = LearnedPD(vg, pg, 10, do_pingpong=pingpong).cuda()
  
training_loss = np.zeros(epochs * len(training) // batch_size)
optimizer = torch.optim.Adam(net.parameters(), lr=1e-4)
criterion = torch.nn.MSELoss()

out_dir='/local/scratch/public/myID/models'

i = 0
for epoch in tqdm(range(epochs)):
    for batch in train_dl:
        inp, tgt = batch
        # Move to gpu and add channel dimension
        inp, tgt = inp.cuda(), tgt.cuda()
        out = net(inp)
        loss = criterion(out, tgt)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        training_loss[i] = loss.item()
        i += 1

        # handle = nvidia_smi.nvmlDeviceGetHandleByIndex(0)
        # info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
        # print("Device {}: {}, Memory : ({:.2f}% free): {}(total), {} (free), {} (used)".format(0, nvidia_smi.nvmlDeviceGetName(handle), 100*info.free/info.total, info.total, info.free, info.used))
torch.save(net.state_dict(), out_dir+"/tomosipoLPD_"+str(epoch+1)+".pt")
```

**Comment by ahendriksen** [comment]
Just a hunch: are you creating a new operator every time you do a forward/backprojection? 

This causes a new ASTRA projector to be created, which might use a small amount of GPU memory.

**Comment by AnderBiguri** [comment]
@ahendriksen In my own code, I wasn't doing that (see my implementation of LDP in the bottom, where I make the operators in the `__init__` function), but it was happening nevertheless. Then I tried your LPD (the code above is essentially https://github.com/ahendriksen/tomosipo/blob/master/notebooks/learned_pd.ipynb) and it is indeed redefining the operator in each forward pass. 

1) consider changing the notebooks such that this is not the case

2) I will try to define the operator once using your code, see what happens. Will let you know soon. 


```

import tomosipo as ts
from tomosipo.torch_support import to_autograd
import torch
import torch.nn as nn
import torch.nn.functional as F
from python_utils.math import power_method
from ts_algorithms import  fdk


class dataProximal(nn.Module):
    """
    """

    def __init__(self, layers, channels):

        super().__init__()
        # imput parsing
        if len(channels) != layers+1:
            raise ValueError(
                "Second input (channels) should have as many elements as layers your network has"
            )
        if layers < 1:
            raise ValueError("At least one layer required")
        # convolutional layers
        layer_list = []
        for ii in range(layers):
            layer_list.append(nn.Conv2d(channels[ii], channels[ii + 1], 3, padding=1, bias=False))
            # Have PReLUs all the way except the last
            if ii < layers - 1:
                layer_list.append(torch.nn.PReLU())
        self.block = nn.Sequential(*layer_list)

    def forward(self, x):
        return self.block(x)


class RegProximal(nn.Module):
    """
    """

    def __init__(self, layers, channels):
        super().__init__()
        if len(channels) != layers+1:
            raise ValueError(
                "Second input (channels) should have as many elements as layers your network has"
            )
        if layers < 1:
            raise ValueError("At least one layer required")

        layer_list = []
        for ii in range(layers):
            layer_list.append(nn.Conv2d(channels[ii], channels[ii + 1], 3,padding=1, bias=False))
            # Have PReLUs all the way except the last
            if ii < layers - 1:
                layer_list.append(torch.nn.PReLU())
        self.block = nn.Sequential(*layer_list)

    def forward(self, x):
        return self.block(x)


class LPD(nn.Module):
    def __init__(
        self,
        n_iters,
        geo,
        mode="ct",
        data_channels=[7, 32, 32, 5],
        reg_channels=[6, 32, 32, 5],
        learned_step=True,
        step_size=None,
    ):
        super().__init__()

        self.geo=geo
        self.n_iters = n_iters
        for i in range(n_iters):
            self.add_module(
                f"{i}_primal", RegProximal(layers=len(reg_channels)-1, channels=reg_channels)
            )
            self.add_module(
                f"{i}_dual", dataProximal(layers=len(data_channels)-1, channels=data_channels)
            )

        self.params = nn.ParameterList(
            [nn.Parameter(torch.randn(10, 10)) for i in range(10)]
        )
        op = self.__make_operators(geo, mode)
        self.op=op
        self.A = to_autograd(op)
        self.AT = to_autograd(op.T)

        if step_size is None:
            # compute step size
            self.step_size = 1 / power_method(op)
        else:
            self.step_size=step_size
        if learned_step:
            self.lambda_dual = nn.ParameterList(
                [nn.Parameter(torch.ones(1) * self.step_size) for i in range(n_iters)]
            )
            self.lambda_primal = nn.ParameterList(
                [nn.Parameter(torch.ones(1) * self.step_size) for i in range(n_iters)]
            )
        else:
            self.lambda_dual = torch.ones(n_iters) * self.step_size
            self.lambda_primal = torch.ones(n_iters) * self.step_size



    @staticmethod
    def __make_operators(geo, mode='ct'):
        if mode.lower() != "ct":
            raise NotImplementedError("Only CT operators supported")
        vg = ts.volume(shape=geo.nVoxel, size=geo.sVoxel)
        pg = ts.cone(
            angles=geo.angles,
            shape=geo.nDetector,
            size=geo.sDetector,
            src_orig_dist=geo.DSO,
            src_det_dist=geo.DSD,
        )
        A = ts.operator(vg, pg)
        return A

    @staticmethod
    def __dual_step(g, h, f, module):
        x = torch.cat((h, f, g), dim=1)
        out = module(x)
        return h + out

    @staticmethod
    def __primal_step(f, update, module):
        x = torch.cat((f, update), dim=1)
        out = module(x)
        return f + out


    def forward(self, g):
        """
        geo: tigre style geo
        """

        B, C, W, H = g.shape

        if C != 1:
            raise NotImplementedError("Only 2D CT images supported")

        # TODO: have a default geo?
        if len(self.geo.angles) != W or self.geo.nDetector[1] != H:
            raise ValueError("geo description and sinogram size do not match")

        # initialize parameters
        h = g.new_zeros(B, 5, W, H)
        f_primal = g.new_zeros(B, 5, *self.geo.nVoxel[1:])
        for i in range(B):
            aux=fdk(self.op, g[i,0])
            for channel in range(5):
                f_primal[i,channel]=aux
        
        for i in range(self.n_iters):
            primal_module = getattr(self, f"{i}_primal")
            dual_module = getattr(self, f"{i}_dual")
            f_dual = self.A(f_primal[:, :1].cpu()).cuda()
            h = self.__dual_step(g, h, f_dual, dual_module)

            update = self.lambda_dual[i]*self.AT(h[:, :1].cpu()).cuda()
            f_primal = self.__primal_step(f_primal, update, primal_module)

        return f_primal[:, 0:1]



```

**Comment by ahendriksen** [comment]
If the OOM happens even when you create only a single tomosipo operator, it could perhaps be an ASTRA memory leak. I am currently not in the position to run the code, so I hope that somebody else can chime in :)

**Comment by AnderBiguri** [comment]
Update:

I ran the code in my first post with 2 modification:

1- dopingpong=True

I get the ASTRA error:

```
Error: Error performing sub-FP
Error: createTextureObject3D: CUDA error 2: out of memory.

Traceback (most recent call last):
  File "/mhome/damtp/r/ab2860/perovskiteCT/perovskiteCT/train_LPD_tomosipo.py", line 160, in <module>
    loss.backward()
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/optim/adam.py", line 141, in step
    F.adam(params_with_grad,
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/optim/_functional.py", line 97, in adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

2 - by creating two attributes `self.op` and `self.opT` and thus only creating an operator once. 

```
Error: Error performing sub-FP

Traceback (most recent call last):
  File "/mhome/damtp/r/ab2860/perovskiteCT/perovskiteCT/train_LPD_tomosipo.py", line 160, in <module>
    loss.backward()
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/local/scratch/public/ab2860/anaconda3/envs/tomosipo/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

If I am not wrong, ASTRA operators are only GPU, right? So when doing "ping-pong" the data goes pytrochGPU->CPU->ASTRA_GPU->CPU->pytorchGPU, right? If that is the case, I am still confused to where the error lies. If the ASTRA projectors for this small scale are run on CPU, then the problem may be in the pytorch side of this code, but I can't see it.

**Comment by D1rk123** [comment]
I'm now looking in to this as well. I tried running the code from your first post on my local machine with only 100 input pairs and I didn't notice an increase in memory use. There was some variation in memory use, but that seemed to be caused by what else I was doing at the moment and it would go back down to the level of when the script was started. To have a more noise free test I'm now testing the code again on a machine in our cluster with 1000 input pairs and no other tasks using GPU memory. I'll probably have some results tomorrow.

Sorry for the late reply. I have turned on email notifications on Github, so I will notice messages more quickly in the future.

**Comment by AnderBiguri** [comment]
@D1rk123 Thanks for the tests! Yes, I did test it with fewer inputs, and I saw very little change. The memory increase I see is very sparse, maybe every 150~200 iterations, I see a few KBs. I have been able to train it with smaller datasets, but with 512^2 images, 360x900 detectors and 5000 datasets, I see the aforementioned 150~iterationwise memory increase. its a tiny one each time, thus the code:

        # handle = nvidia_smi.nvmlDeviceGetHandleByIndex(0)
        # info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
        # print("Device {}: {}, Memory : ({:.2f}% free): {}(total), {} (free), {} (used)".format(0, nvidia_smi.nvmlDeviceGetName(handle), 100*info.free/info.total, info.total, info.free, info.used))
, it smuch more accurate for memory reporting.

**Comment by D1rk123** [comment]
To give a better overview over time I'm storing the minimum and maximum level that occurred over each epoch and storing it in a file:

`i = 0
mem_use_log = []
for epoch in tqdm(range(epochs)):
    batch_mem_used = []
    for batch in train_dl:
        inp, tgt = batch
        # Move to gpu and add channel dimension
        inp, tgt = inp.cuda(), tgt.cuda()
        out = net(inp)
        loss = criterion(out, tgt)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        training_loss[i] = loss.item()
        i += 1

        handle = nvidia_smi.nvmlDeviceGetHandleByIndex(0)
        info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
        batch_mem_used.append(info.used)
        #print("Device {}: {}, Memory : ({:.2f}% free): {}(total), {} (free), {} (used)".format(0, nvidia_smi.nvmlDeviceGetName(handle), 100*info.free/info.total, info.total, info.free, info.used))
        
    print(f"This epoch used memory fluctuated between {min(batch_mem_used)} and {max(batch_mem_used)}")
    mem_use_log.append((min(batch_mem_used), max(batch_mem_used)))
    with open(out_dir+"/mem_use_log.csv", "w") as file:
        for mem_log_step in mem_use_log:
            file.write(f"{mem_log_step[0]},{mem_log_step[1]}\n")`

**Comment by AnderBiguri** [comment]
Thanks! In my case I always see it go up. Unfortunately I just checked and I have deleted the log file. I can make a new one if needed

**Comment by D1rk123** [comment]
Thanks! I think I'll wait for my test to finish first, which should be tomorrow morning. If that brings up more questions I would like to see your logfile.

**Comment by AnderBiguri** [comment]
Yes, that is what I see. The error message comes from ASTRA itself, but it is quite a standard "tried to allocate, no memory available".

**Comment by D1rk123** [comment]
I'm not sure yet what is causing the memory leak, but I have managed to make a smaller faster example, where I can change one line to have a memory leak or not:

```
import torch 
import tomosipo as ts
from tomosipo.torch_support import (
    to_autograd,
)
import torch.nn as nn
import numpy as np
from tqdm import tqdm
import nvidia_smi

class NonsenseNetwork(nn.Module):
    def __init__(self, vg, pg, n_iters, do_pingpong=False):
        super().__init__()
        self.n_iters = n_iters
        self.vg = vg
        self.pg = pg

        self.ts_op = ts.operator(self.vg[:1], self.pg.to_vec()[:, :1, :])
        self.op = to_autograd(self.ts_op)
        self.opT = to_autograd(self.ts_op.T)
        self.conv = nn.Conv2d(1, 1, kernel_size=3, padding=1, bias=False)
                
    def forward(self, g):
        B, C, H, W = g.shape
        assert C == 1, "single channel support only for now"
        
        #no memory leak
        #return self.conv(self.opT(g))
        #memory leak
        return self.opT(self.conv(g))

# GEOMETRY
vg = ts.volume(shape=(1,128,128), size=(300/128, 300, 300))
pg = ts.cone(
    angles=90, shape=(1, 225), size=(1, 900), src_orig_dist=575, src_det_dist=1050
)
A = ts.operator(vg, pg)

# DATA
n_files=5000

y=torch.zeros((n_files,*A.range_shape), dtype=torch.float32)
x=torch.zeros((n_files,*A.domain_shape), dtype=torch.float32)

# TRAIN
epochs = 10
batch_size = 3
out_dir='output'

training_ds=torch.utils.data.TensorDataset(y,x)
train_dl = torch.utils.data.DataLoader(training_ds, batch_size=batch_size, shuffle=False, pin_memory=True, drop_last=True)
net = NonsenseNetwork(vg, pg, 10).cuda()
optimizer = torch.optim.Adam(net.parameters(), lr=1e-4)
criterion = torch.nn.MSELoss()

nvidia_smi.nvmlInit()
handle = nvidia_smi.nvmlDeviceGetHandleByIndex(0)

mem_use_log = []
for epoch in tqdm(range(epochs)):
    batch_mem_used = []
    for batch in train_dl:
        inp, tgt = batch
        # Move to gpu and add channel dimension
        inp, tgt = inp.cuda(), tgt.cuda()
        out = net(inp)
        loss = criterion(out, tgt)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
        batch_mem_used.append(info.used)
        
    print(f"This epoch used memory fluctuated between {min(batch_mem_used)} and {max(batch_mem_used)}")
    mem_use_log.append((min(batch_mem_used), max(batch_mem_used)))
    with open(out_dir+"/mem_use_log.csv", "w") as file:
        for mem_log_step in mem_use_log:
            file.write(f"{mem_log_step[0]},{mem_log_step[1]}\n")
```

**Comment by AnderBiguri** [comment]
Interesting. How does it behave if you have another operation after the no memory leak? I.e. could you make something like:

`return self.op(self.conv(self.opT(g)))
`
or even

`return self.opT(self.op(self.conv(self.opT(g))))
`
Or is the memory leak coming from that conv - tomosipo interface?

**Comment by D1rk123** [comment]
I have tried this and it also causes the memory leak:
```
return self.opT(self.op(self.conv(self.opT(g)))) 
```

**Comment by D1rk123** [comment]
When you change the cone beam geometry to a parallel beam geometry there is no memory leak anymore. This explains why @ahendriksen and me didn't run into this problem earlier in our experiments. This also suggests that this problem might be a bug in Astra.

I also tried replacing the to_autograd function with a slightly modified version of the OperatorFunction class from tomosipo.torch_support, which used a hardcoded operator instead of the ctx variable to see if maybe that was where the memory leak was caused, but that didn't solve the memory leak.

**Comment by AnderBiguri** [comment]
@D1rk123 I see. I was about to try to change the code to ODL operators, to see how it compares, and see if still happens. The backend code should be the same, right? 

I noticed that ODL and tomosipo have different reference points for angles and images/singorams. Do you know what is the geo conversion that I need to do from one to the other (so I can try it with my data)? I can figure it out myself, of course, just trying to skip the task if you have the information at hand.

**Comment by AnderBiguri** [comment]
Hi @D1rk123 . All that sounds great. Do let me know how it goes. This is code I am using in a project where Joost Batemburg and Daniel Pelt are collaborators, so also do let me know if you pinpoint something and want me to raise this with them.

**Comment by D1rk123** [comment]
I see the same behavior in Astra without Tomosipo. In this example the memory use is also increasing over time at about the same rate.

```
import numpy as np
import astra
from tqdm import tqdm
import nvidia_smi

nvidia_smi.nvmlInit()
handle = nvidia_smi.nvmlDeviceGetHandleByIndex(0)

log_file='output/mem_use_log.csv'

num_epochs = 50
num_batches = 5000

## astra  projector
vol_geom = astra.create_vol_geom(1,128,128)

#create_proj_geom('cone', detector_spacing_x, detector_spacing_y, det_row_count, det_col_count, angles, source_origin, origin_det)
proj_geom = astra.creators.create_proj_geom(
    'cone',
    1,    # detector_spacing_x
    1,    # detector_spacing_y
    1,    # det_row_count
    256,  # det_col_count
    64,   # angles
    1024, # source_origin
    0     # origin_det
)
phantom_id = astra.data3d.create('-vol', vol_geom, data=np.zeros((128, 1, 128), dtype=np.float32))

mem_use_log = []
for i in tqdm(range(num_epochs)):
    for j in range(num_batches):
        projections_id, projections = astra.creators.create_sino3d_gpu(phantom_id, proj_geom, vol_geom)
            
    info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
    mem_use_log.append(info.used)
    print(f"Current memory use {mem_use_log[-1]}")
    
    with open(log_file, "w") as file:
        for mem_log_step in mem_use_log:
            file.write(f"{mem_log_step}\n")
```

**Comment by AnderBiguri** [comment]
We should open an ASTRA issue then. I assume ODL also has the same issue, if it comes from the backend. 
Should I open the issue at the github repo, or will you tell Willem?

**Comment by D1rk123** [comment]
I am planning to ask him in person on Monday when I'm at the office again.

Now that I think of it, in ODL you may be able to use a different part of Astra. Astra has 3D operators on the GPU, and 2D operators on the CPU, which have a bit more options for interpolators. Tomosipo only uses the 3D GPU accelerated operators, and ODL seems to support both.

**Comment by wjp** [comment]
Thanks for the report and easy reproduction script! This was a bug in Astra that was introduced in 2.1.0 and is now fixed in git in astra-toolbox/astra-toolbox@1f7e98f8e389bde4f48b2d21e0c37660a61e140c . I'll try to make time to do a release 2.1.1 for Astra this or next week with this fix.

P.S. In the innermost loop in the Astra-only reproduction script above you need a line `astra.data3d.delete(projections_id)` to avoid a host memory leak.

**Comment by D1rk123** [comment]
Tomosipo is Python only, so it does need to be rebuild. Just update Astra in your conda environment, when an Astra version with the fix available

**Comment by AnderBiguri** [comment]
@D1rk123 I assume you meant "It doesn't" there?

**Comment by D1rk123** [comment]
True

**Comment by AnderBiguri** [comment]
Hi @wjp , 
Sorry for the push, but do you have any idea when you expect to have time to get ASTRA 2.1.1 out?
I know I can upgrade to master with pip, but its not really suggested to have conda+pip, it can break.

**Comment by wjp** [comment]
Should be later this week.

**Comment by wjp** [comment]
Linux/Windows conda packages for astra 2.1.1 are now available.

**Comment by D1rk123** [comment]
I've reran the Tomosipo projection test code from a couple of messages ago with the newest version of Astra (2.1.1), and the memory is no longer increasing and the script is no longer terminated because of an out of memory exception so I consider this bug fixed.

**Comment by AnderBiguri** [comment]
Can confirm! This is fixed!

**Comment by D1rk123** [comment]
@AnderBiguri In the new v0.6.0 release of Tomosipo I have modified the interface of the to_autograd function. By default it now returns a 3D operator that does not include batch or channel dimensions, just like a normal Tomosipo operator. For use in a 2D Pytorch neural network use:
```
to_autograd(operator, num_extra_dims=2, is_2d=True)
```
Apart from adding these two arguments to every to_autograd call, no other changes to your code are necessary.
